export const FETCH_LIBRARY = 'FETCH_LIBRARY';
export const FETCH_SONG = 'FETCH_SONG';
export const SELECT_SONG = 'SELECT_SONG';
export const DESELECT_SONG = 'DESELECT_SONG';
export const LOAD_FROM_PLAYLIST = 'LOAD_FROM_PLAYLIST';

export const FETCH_SETS = 'FETCH_SETS';
export const SELECT_PLAYLIST = 'SELECT_PLAYLIST';
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const EDIT_PLAYLIST = 'EDIT_PLAYLIST';

export const CLEAR_SELECTED = 'CLEAR_SELECTED';
export const COMPLETE_ALL = 'COMPLETE_ALL';

export const CREATE_ERROR = 'CREATE_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
